language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

branches:
  only:
  - staging
  - trying
  - master

services:
  - docker

cache: cargo

install:
  - cargo install diesel_cli --force
  - diesel --version

before_script:
# Copy testing env file if one exists
  - if [[ -f .env.testing ]]; then cp .env.testing .env; fi

  - docker run --name schani_import_db --env-file .env -p 54322:5432 -d postgres
  # docker run --hostname schani_processing_queue -p 8081:15672 --name schani_processing_queue -p 5672:5672 -d rabbitmq:3-management

script:
  # Build
  - cargo build --verbose

  # Migrate
  - diesel migration run
  - diesel migration redo

  # Test
  - cargo test --verbose

