from debian:latest

RUN apt-get update && \
       apt-get install -y \
       libpq5 \
       --no-install-recommends

VOLUME ["/schani_import"]

EXPOSE 8000

ENTRYPOINT ["/schani_import/webservice"]
